### PR TITLE
Missing close icon on editor tabs

### PR DESCRIPTION
**Pull request by JohnMurga**
It seems to have disappeared a while ago :-)

### CODE REVIEW

**Comment by dtrillo** [comment]
If you click on the tab after the text, the tab will close. Icon is not needed although you have the funcionality available.

**Comment by jbaron** [comment]
Which theme and version of CATS are you using?

(it seems indeed to be missing depending on the theme you are using, so just want to make sure)

**Comment by dtrillo** [comment]
i am using "Modern" theme, and I see no close icon (the same as with Classic theme).
If you use the other themes, you'll find the icons!

**Comment by jbaron** [comment]
Thanks for the patch!

**Pull request merged**
